apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: drimdev/api-gateway:otel
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: Clients__BankingService
          value: http://banking-service:80
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(NODE_IP):4317
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
  - port: web
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-gateway
  namespace: default
spec:
  commonName: drim.city
  secretName: api-gateway-cert
  dnsNames:
  - drim.city
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-api
  namespace: default
spec:
  stripPrefix:
    prefixes:
    - /api
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-gateway
  namespace: default
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`drim.city`) && PathPrefix(`/api`)
    services:
    - name: api-gateway
      port: 80
    middlewares:
    - name: strip-prefix-api
      namespace: default
  tls:
    secretName: api-gateway-cert
