apiVersion: v1
kind: Service
metadata:
  name: banking-service
  labels:
    app: banking-service
spec:
  ports:
  - port: 80
    name: grpc
  - port: 81
    name: web
  selector:
    app: banking-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: banking-service
    spec:
      containers:
      - name: banking-service
        image: drimdev/banking-service:otel
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 80
        - name: web
          containerPort: 81
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: host
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: password
        - name: ConnectionStrings__BankingDbContext
          value: Host=$(POSTGRES_HOST);Database=BankingService;Username=$(POSTGRES_USERNAME);Password=$(POSTGRES_PASSWORD);Maximum Pool Size=100;Connection Idle Lifetime=60;
        - name: Clients__BlockchainService
          value: http://blockchain-service:80
        - name: Kestrel__Endpoints__Http__Url
          value: http://+:81
        - name: Kestrel__Endpoints__Http__Protocols
          value: Http1
        - name: Kestrel__Endpoints__gRPC__Url
          value: http://+:80
        - name: Kestrel__Endpoints__gRPC__Protocols
          value: Http2
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(NODE_IP):4317
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: banking-service
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: banking-service
  endpoints:
  - port: web
