apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
  labels:
    app: blockchain-service
spec:
  ports:
  - port: 80
    name: grpc
  - port: 81
    name: web
  selector:
    app: blockchain-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blockchain-service
    spec:
      containers:
      - name: blockchain-service
        image: drimdev/blockchain-service:otel
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 80
        - name: web
          containerPort: 81
        env:
        - name: Kestrel__Endpoints__Http__Url
          value: http://+:81
        - name: Kestrel__Endpoints__Http__Protocols
          value: Http1
        - name: Kestrel__Endpoints__gRPC__Url
          value: http://+:80
        - name: Kestrel__Endpoints__gRPC__Protocols
          value: Http2
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(NODE_IP):4317
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blockchain-service
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: blockchain-service
  endpoints:
  - port: web
